[package]
name = "builders_and_biomes"
version = "0.1.0"
authors = ["Luminoso-256 <github.com/Luminoso-256>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.0-alpha.14"
rand = "0.7.3"